### ISSUE TITLE
404 page not showing - server panics instead

### ISSUE THREAD

**Issue by adamkiss** [tempestphp/tempest-framework#1805]
### Tempest version

2.9.1

### PHP version

8.4

### Operating system

macOS

### Description

404 Pages are not showing, instead Router panics and throws 500. You can see it even on the Tempest Framework site.

Additionally, if I set `ENVIRONMENT` to `production` the missing route returns `200 OK`, but the content leaks paths/errors:

```
<b>Fatal error</b>:  Uncaught Tempest\Http\HttpRequestFailed: Failed request: 404 Not Found in /[PATH]/vendor/tempest/framework/packages/router/src/HandleRouteExceptionMiddleware.php:28
```
### Steps to reproduce

Open https://tempestphp.com/asdasdasd

**Comment by innocenzi** [comment]
Caused by https://github.com/tempestphp/tempest-framework/pull/1624 it seems, cc @brendt

**Comment by innocenzi** [comment]
Specifying `false` prevents autoloading, so `class_exists` may just return `false`. Hence, we will not register any exception handler.

**Comment by brendt** [comment]
Should be fixed in 2.14.0

**Comment by adamkiss** [comment]
@brendt is tempestphp.com supposed to show error 500 page on 404?

**Comment by brendt** [comment]
Yes, that's because of a catchall route which we need to fix on the project level (or maybe the framework, but unrelated to this)

**Comment by adamkiss** [comment]
@brendt Cool! I'm on the road, so I couldn't double check http code

**Comment by adamkiss** [comment]
@brendt @innocenzi This is definitely still not working as intended.

Following the [docs on custom error page](https://tempestphp.com/2.x/features/exception-handling#customizing-the-error-page), I created a [minimal repro where home returns `NotFound`](https://github.com/adamkiss/tempest-404-fail), and instead of `GenericResponse` with 404 status, I still get an uncaught `HttpRequestFailed` exception thrown.  

Is this something else?

Edit: If I switch from local to production environment, I actually do get 404 page with 404 status (wooo!), but it's the default Tempest 404, not my custom `GenericResponse`

**Comment by xHeaven** [comment]
> [@brendt](https://github.com/brendt) [@innocenzi](https://github.com/innocenzi) This is definitely still not working as intended.
> 
> Following the [docs on custom error page](https://tempestphp.com/2.x/features/exception-handling#customizing-the-error-page), I created a [minimal repro where home returns `NotFound`](https://github.com/adamkiss/tempest-404-fail), and instead of `GenericResponse` with 404 status, I still get an uncaught `HttpRequestFailed` exception thrown.
> 
> Is this something else?
> 
> Edit: If I switch from local to production environment, I actually do get 404 page with 404 status (wooo!), but it's the default Tempest 404, not my custom `GenericResponse`

What if you put the `#[Priority(Priority::EXCEPTION_HANDLING)]` attribute on top of your middleware?

**Comment by adamkiss** [comment]
@xHeaven That works! 🎉 

Is the low priority of custom middleware expected behavior? If yes, it should be probably mentioned with the middleware example, otherwise the example just doesn't work.

**Comment by xHeaven** [comment]
> @xHeaven That works! 🎉 
> 
> Is this the low priority of custom middleware expected behavior? If yes, it should probably go to documentation with the middleware example

In this case I think it's expected behavior, because this attribute puts the middleware down to the "exception handling" level, exactly where we want it. If this is the case, I think the documentation is missing this.

I'd like some additional input whether I am right or not, though.
CC @innocenzi @brendt
